[metadata]
name = sionna
version = attr: sionna.__version__
author = The Sionna contributors
author_email = sionna@nvidia.com
description = Ray-based electromagnetic scattering and blockage modeling with extensions to Sionna RT
long_description = file: README.md
long_description_content_type = text/markdown
license = Apache 2.0
url = https://github.com/AinurZiga/sionna-RT-reflectivity
project_urls =
    Bug Tracker = https://github.com/AinurZiga/sionna-RT-reflectivity/issues
classifiers =
    Programming Language :: Python :: 3
    Intended Audience :: Science/Research
    Intended Audience :: Telecommunications Industry
    License :: OSI Approved :: Apache Software License

[options]
packages = find:
include_package_data = True
python_requires = >=3.11
install_requires =
    tensorflow==2.21.0
    mitsuba==3.5.0
    drjit==0.4.4
    numpy==2.2.6
    scipy==1.17.1
    trimesh==5.1.1
    matplotlib
    importlib_resources
    pythreejs >= 2.4.2
    ipywidgets >= 8.0.4
    ipydatawidgets == 4.3.2
    jupyterlab-widgets == 3.0.5

[options.package_data]
* =
    *.csv
    *.npy
    *.npz
    *.json
    *.xml
    *.ply
sionna =
    rt/data/*.npy
    rt/data/*.npz
    rt/scenes/*/*.xml
    rt/scenes/*/meshes/*.ply